### ISSUE TITLE
Some Usage Guidance

### ISSUE THREAD

**Issue by Fake10086** [zxy556677/EasyGen#3]
Great Work! Can you provide a brief introduction on how to install the packages and how to use proper weights to do image generation? Thx a lot.

**Comment by zxy556677** [comment]
Thanks for your advice, we will add the requirment.txt and guidance, also the weights for image generation will upload recently!

**Comment by zxy556677** [comment]
We have upload the environment requirments and introduction to use inference code for multimodal dialogue generation!
